---
# tasks file for tower
- name: install some useful packages 
  apt: pkg={{ item }} state=latest
  with_items: tower_dependencies

- name: pip ansible install
  pip: name=ansible

- name: download Tower setup
  get_url: url=http://releases.ansible.com/ansible-tower/setup/ansible-tower-setup-latest.tar.gz dest=/tmp/ force=yes

- name: extract Tower
  command: chdir=/tmp/ creates=/tmp/ansible-tower-setup-{{tower_version}} tar zxvf ansible-tower-setup-latest.tar.gz

- name: run the Tower installer
  command: chdir=/tmp/ansible-tower-setup-{{tower_version}} creates=/etc/awx/settings.py ./setup.sh
