---
# tasks file for tower
- name: install some useful packages 
  yum: name={{ item }} state=latest
  with_items:
  - git
  - supervisor
  - python-pip
  - python-jinja2
  - python-devel
  - unzip

- name: pip ansible install
  action: command pip install ansible
  sudo: yes

- name: download Tower setup
  get_url: url=http://releases.ansible.com/ansible-tower/setup/ansible-tower-setup-{{tower_version}}.tar.gz dest=/opt/ force=yes

- name: extract Tower
  command: chdir=/opt/ creates=/opt/ansible-tower-setup-{{tower_version}} tar zxvf ansible-tower-setup-{{tower_version}}.tar.gz

- name: run the Tower installer
  command: chdir=/opt/ansible-tower-setup-{{tower_version}} creates=/etc/awx/settings.py ./setup.sh
